base/urls.py
#  MIT License
#
#  Copyright (c) 2022 Ian Buttimer
#
#  Permission is hereby granted, free of charge, to any person obtaining a copy
#  of this software and associated documentation files (the "Software"), to
#  deal in the Software without restriction, including without limitation the
#  rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
#  sell copies of the Software, and to permit persons to whom the Software is
#  furnished to do so, subject to the following conditions:
#
#  The above copyright notice and this permission notice shall be included in
#  all copies or substantial portions of the Software.
#
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
#  FROM,OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
#  DEALINGS IN THE SOFTWARE.

"""soapbox URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.urls import path

from opinions.views.opinion_list import (
    OpinionCategoryFeed, OpinionFollowedFeed, OpinionAllFeed
)
from soapbox import BASE_APP_NAME, val_test_url, val_test_route_name
from .constants import (
    FOLLOWING_FEED_URL, FOLLOWING_FEED_ROUTE_NAME,
    CATEGORY_FEED_URL, CATEGORY_FEED_ROUTE_NAME, ALL_FEED_URL,
    ALL_FEED_ROUTE_NAME,
)

app_name = BASE_APP_NAME

urlpatterns = [
    # val-test urls
    path(val_test_url(FOLLOWING_FEED_URL), OpinionFollowedFeed.as_view(),
         name=val_test_route_name(FOLLOWING_FEED_ROUTE_NAME)),
    path(val_test_url(CATEGORY_FEED_URL), OpinionCategoryFeed.as_view(),
         name=val_test_route_name(CATEGORY_FEED_ROUTE_NAME)),

    # standard app urls
    path(FOLLOWING_FEED_URL, OpinionFollowedFeed.as_view(),
         name=FOLLOWING_FEED_ROUTE_NAME),
    path(CATEGORY_FEED_URL, OpinionCategoryFeed.as_view(),
         name=CATEGORY_FEED_ROUTE_NAME),
    path(ALL_FEED_URL, OpinionAllFeed.as_view(),
         name=ALL_FEED_ROUTE_NAME),
]

soapbox/urls.py
#  MIT License
#
#  Copyright (c) 2022 Ian Buttimer
#
#  Permission is hereby granted, free of charge, to any person obtaining a copy
#  of this software and associated documentation files (the "Software"), to
#  deal in the Software without restriction, including without limitation the
#  rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
#  sell copies of the Software, and to permit persons to whom the Software is
#  furnished to do so, subject to the following conditions:
#
#  The above copyright notice and this permission notice shall be included in
#  all copies or substantial portions of the Software.
#
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
#  FROM,OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
#  DEALINGS IN THE SOFTWARE.

"""soapbox URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from allauth.account import views
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from soapbox import (
    ADMIN_URL, ACCOUNTS_URL, SUMMERNOTE_URL,
    USERS_URL, USER_APP_NAME,
    OPINIONS_URL, OPINIONS_APP_NAME,
    settings, BASE_APP_NAME, val_test_url, val_test_route_name
)
from soapbox.constants import FEED_URL

urlpatterns = [
    # val-test urls for allauth paths
    path(val_test_url("signup/"), views.signup,
         name=val_test_route_name("account_signup")),
    path(val_test_url("login/"), views.login,
         name=val_test_route_name("account_login")),
    path(val_test_url("logout/"), views.logout,
         name=val_test_route_name("account_logout")),

    # standard app urls
    path(ADMIN_URL, admin.site.urls),
    path(SUMMERNOTE_URL, include('django_summernote.urls')),
    path(ACCOUNTS_URL, include('allauth.urls')),
    path(USERS_URL, include(f'{USER_APP_NAME}.urls')),
    path(OPINIONS_URL, include(f'{OPINIONS_APP_NAME}.urls')),
    path(FEED_URL, include(f'{BASE_APP_NAME}.urls')),
    path('', include(f'{BASE_APP_NAME}.root_urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

user/urls.py
#  MIT License
#
#  Copyright (c) 2022 Ian Buttimer
#
#  Permission is hereby granted, free of charge, to any person obtaining a copy
#  of this software and associated documentation files (the "Software"), to
#  deal in the Software without restriction, including without limitation the
#  rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
#  sell copies of the Software, and to permit persons to whom the Software is
#  furnished to do so, subject to the following conditions:
#
#  The above copyright notice and this permission notice shall be included in
#  all copies or substantial portions of the Software.
#
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
#  FROM,OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
#  DEALINGS IN THE SOFTWARE.
#

from django.urls import path

from soapbox import USER_APP_NAME, val_test_url, val_test_route_name

from .constants import (
    USER_ID_URL, USER_ID_ROUTE_NAME, USER_USERNAME_URL,
    USER_USERNAME_ROUTE_NAME
)
from . import views


# https://docs.djangoproject.com/en/4.1/topics/http/urls/#url-namespaces-and-included-urlconfs
app_name = USER_APP_NAME

urlpatterns = [
    # val-test urls
    path(val_test_url(USER_USERNAME_URL),
         views.UserDetailByUsername.as_view(),
         name=val_test_route_name(USER_USERNAME_ROUTE_NAME)),

    # standard app urls
    path(USER_ID_URL, views.UserDetailById.as_view(), name=USER_ID_ROUTE_NAME),
    path(USER_USERNAME_URL, views.UserDetailByUsername.as_view(),
         name=USER_USERNAME_ROUTE_NAME),
]

user/models.py
#  MIT License
#
#  Copyright (c) 2022 Ian Buttimer
#
#  Permission is hereby granted, free of charge, to any person obtaining a copy
#  of this software and associated documentation files (the "Software"), to
#  deal in the Software without restriction, including without limitation the
#  rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
#  sell copies of the Software, and to permit persons to whom the Software is
#  furnished to do so, subject to the following conditions:
#
#  The above copyright notice and this permission notice shall be included in
#  all copies or substantial portions of the Software.
#
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
#  FROM,OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
#  DEALINGS IN THE SOFTWARE.

from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _
from cloudinary.models import CloudinaryField

from soapbox import AVATAR_FOLDER, DEVELOPMENT
from categories.models import Category
from utils import ModelMixin

from .constants import (
    FIRST_NAME, LAST_NAME, BIO, AVATAR, CATEGORIES, PREVIOUS_LOGIN
)


class User(ModelMixin, AbstractUser):
    """
    Custom user model
    (Recommended by
    https://docs.djangoproject.com/en/4.1/topics/auth/customizing/#auth-custom-user)
    """

    # field names
    FIRST_NAME_FIELD = FIRST_NAME
    LAST_NAME_FIELD = LAST_NAME
    # EMAIL_FIELD and USERNAME_FIELD inherited from AbstractUser
    PASSWORD_FIELD = 'password'
    BIO_FIELD = BIO
    AVATAR_FIELD = AVATAR
    CATEGORIES_FIELD = CATEGORIES
    PREVIOUS_LOGIN_FIELD = PREVIOUS_LOGIN

    AVATAR_BLANK = 'avatar_blank'

    # Values copied from django.contrib.auth.models.py::AbstractUser
    USER_ATTRIB_FIRST_NAME_MAX_LEN: int = 150
    USER_ATTRIB_LAST_NAME_MAX_LEN: int = 150
    USER_ATTRIB_USERNAME_MAX_LEN: int = 150
    # Values copied from django.db.models.fields::EmailField
    USER_ATTRIB_EMAIL_MAX_LEN: int = 254
    # Values copied from cloudinary.models::CloudinaryField
    USER_ATTRIB_AVATAR_MAX_LEN: int = 255

    USER_ATTRIB_BIO_MAX_LEN: int = 250
    USER_ATTRIB_CATEGORIES_MAX_LEN: int = 250

    bio = models.CharField(_('biography'), max_length=USER_ATTRIB_BIO_MAX_LEN,
                           blank=True)

    # by the time the 'user_logged_in' signal is received the 'last_login'
    # field in AbstractBaseUser has already been updated to the current login
    previous_login = models.DateTimeField(
        _("previous login"), blank=True, null=True)

    # ImageField for local dev, CloudinaryField for production
    # https://cloudinary.com/documentation/django_image_and_video_upload#django_forms_and_models
    avatar = models.ImageField(
        _('image'), default=AVATAR_BLANK, upload_to=AVATAR_FOLDER, blank=True
    ) if DEVELOPMENT else CloudinaryField(
        _('image'), default=AVATAR_BLANK, folder=AVATAR_FOLDER)

    categories = models.ManyToManyField(Category)

    class Meta:
        ordering = ["date_joined"]

    def __str__(self):
        return self.username

    def __repr__(self):
        return f'{self.model_name()}[{self.id}]: {str(self)}'

templates/user/profile.html
{% extends "base.html" %}

{% load i18n %}
{% load static %}
{% load form_field %}

{% block head_title %}SoapBox - Profile{% endblock %}

{% block extra_css %}
    <!-- include summernote css - use bootstrap4 to match settings.SUMMERNOTE_THEME -->
    <link href="{% static 'summernote/summernote-bs4.min.css' %}" rel="stylesheet" type="text/css">
{% endblock extra_css %}

{% block extra_js_head %}
    <script src="https://code.jquery.com/jquery-3.6.1.min.js" integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script type="text/javascript" src="{% static 'jquery/jquery-3.6.1.min.js' %}"><\/script>')</script>
{% endblock extra_js_head %}

{% block content %}
<article class="row">
    <div class="col-12 mt-2 text-center">
        <h1>{% trans "Profile" %} <em>{{ user_profile.username }}</em></h1>

        <form
            {% if not read_only %}
                method="post" action="{% url 'user:user_id' user_profile.id %}" enctype="multipart/form-data"
            {% endif %}
        >
            {% if not read_only %}
                {% csrf_token %}
            {% endif %}

            {% include "snippet/form_errors.html" %}

            <fieldset
                    {% if read_only %}
                    disabled
                    {% endif %}
            >
                <div class="row mb-3">
                    <div class="col-6">
                        {# basic user form fields #}

                        {% for field in form %}
                            {% if field.name in lhs_fields %}
                                <div class="row mb-3">
                                    <div class="col-sm-4 text-start">
                                        <label for="id_{{ field.name }}" class="col-form-label">{{ field.label }}</label>
                                    </div>
                                    <div class="col-sm-8">
                                        {{ field }}
                                    </div>
                                </div>
                            {% endif %}
                        {% endfor %}
                    </div>

                    <div class="col-6">
                        {# user avatar field #}
                        <div class="preview">
                            <img src="{{ avatar_url }}" width="100" height="100" alt="Avatar image">
                        </div>
                        {% if not read_only %}
                            {% form_field form 'avatar' as avatar_field %}
                            {{ avatar_field }}
                        {% endif %}
                    </div>
                </div>

                {% if not val_test %}
                {# exclude summernote for html test as its fails the W3C Nu Html Checker #}
                    {% form_field form 'bio' as bio_field %}
                    <div class="row mb-3">
                        <div class="col-sm-2 text-start">
                            <label for="{{ bio_field.auto_id }}" class="form-label">{{ bio_field.label }}</label>
                        </div>
                        <div class="col-sm-10">
                            {% if read_only %}
                                <div id="readonly_content" class="text-start">
                                    {# content replaced #}
                                </div>
                            {% else %}
                                {{ bio_field }}
                            {% endif %}
                        </div>
                    </div>
                {% endif %}

                {% form_field form 'categories' as categories_field %}
                <div class="row mb-3">
                    <div class="col-sm-2 text-start">
                        <label id="followed-categories" for="{{ categories_field.auto_id }}" class="form-label">{{ categories_field.label }}</label>
                    </div>
                    <div class="col-sm-10">
                        <p>Categories selected here will populate the <a href="{% url 'base:category_feed' %}" aria-label="display category opinion feed">Category Feed</a>.</p>
                        {% if read_only %}
                            <ul class="list-group list-group-horizontal-sm">
                                {% for category in categories_field.initial %}
                                    <li class="list-group-item li__category">{{ category }}</li>
                                {% endfor %}
                            </ul>
                        {% else %}
                            {{ categories_field }}
                        {% endif %}
                    </div>
                </div>

                {% if is_super %}
                    {% form_field form 'groups' as groups_field %}
                    <div class="row mb-3">
                        <div class="col-sm-2 text-start">
                            <label for="{{ groups_field.auto_id }}" class="form-label">{{ groups_field.label }}</label>
                        </div>
                        <div class="col-sm-10">
                            {{ groups_field }}
                        </div>
                    </div>
                {% endif %}
            </fieldset>

            {% if not read_only %}
                <div class="row mb-3">
                    <div class="col-sm-2 offset-sm-3">
                        <a class="btn btn-dark mb-1 btn__text" href="{% url 'home' %}">{% trans "Cancel" %}</a>
                    </div>
                    <div class="col-sm-2 offset-sm-2">
                        <button type="submit" class="btn btn-primary btn__text">{% trans "Update" %}</button>
                    </div>
                </div>
            {% endif %}
        </form>
    </div>
</article>

{% endblock content %}

{% block extra_js_body %}
    <!-- include summernote js - use bootstrap4 to match settings.SUMMERNOTE_THEME -->
    <script src="{% static 'summernote/summernote-bs4.min.js' %}"></script>
    <!-- lazy loading summernote need to call initSummernote -->
<!--    <script>-->
<!--        $(document).ready(function() {-->
<!--            initSummernote_id_bio();-->
<!--        });-->
<!--    </script>-->

    {% if read_only %}
        <script>
                $(document).ready(function() {
                    {% form_field form 'bio' as bio_field %}
                    $('#readonly_content').html('{{ bio_field.initial | safe }}');
                });
        </script>
    {% endif %}
    <script>
        /* Update preview image when file selected.
           Based on https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#examples */

        const input = document.querySelector('#id_avatar'); /* file input */
        const preview = document.querySelector('.preview'); /* div containing preview image */

        function updateImageDisplay() {
            /* Update avatar preview */
            const curFiles = input.files;
            if (curFiles.length === 0) {
                alert("No files currently selected for upload");
            } else {
                for (const file of curFiles) {
                    if (validFileType(file)) {
                        $(".preview img").prop("src", URL.createObjectURL(file));
                    } else {
                        alert(`${file.name} is not a valid file type. Please update your selection.`);
                    }
                }
            }
        }

        // https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types
        const fileTypes = [
            {% for a in image_file_types %}
                "{{ a }}"{% if forloop.revcounter0 > 0 %},{% endif %}
            {% endfor %}
        ];

        function validFileType(file) {
          return fileTypes.includes(file.type);
        }

        function returnFileSize(number) {
          if (number < 1024) {
            return `${number} bytes`;
          } else if (number >= 1024 && number < 1048576) {
            return `${(number / 1024).toFixed(1)} KB`;
          } else if (number >= 1048576) {
            return `${(number / 1048576).toFixed(1)} MB`;
          }
        }

        $(document).ready(function() {
            $('#id_avatar').on('change',
                function(e) {
                    updateImageDisplay();
                });
        });
    </script>


{% endblock extra_js_body %}

templates/user/profile_view.html
<!--
  ~ MIT License
  ~
  ~ Copyright (c) 2022 Ian Buttimer
  ~
  ~ Permission is hereby granted, free of charge, to any person obtaining a copy
  ~ of this software and associated documentation files (the "Software"), to deal
  ~ in the Software without restriction, including without limitation the rights
  ~ to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  ~ copies of the Software, and to permit persons to whom the Software is
  ~ furnished to do so, subject to the following conditions:
  ~
  ~ The above copyright notice and this permission notice shall be included in
  ~ all copies or substantial portions of the Software.
  ~
  ~ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  ~ IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  ~ FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  ~ AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  ~ LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  ~ OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
  ~ SOFTWARE.
  -->

{% extends "base.html" %}

{% load i18n %}
{% load static %}

{% block head_title %}SoapBox - Profile{% endblock %}

{% block extra_css %}
    <!-- include summernote css - use bootstrap4 to match settings.SUMMERNOTE_THEME -->
    <link href="{% static 'summernote/summernote-bs4.min.css' %}" rel="stylesheet">
{% endblock extra_css %}

{% block extra_js_head %}
    <script src="https://code.jquery.com/jquery-3.6.1.min.js" integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script type="text/javascript" src="{% static 'jquery/jquery-3.6.1.min.js' %}"><\/script>')</script>
{% endblock extra_js_head %}

{% block content %}
<div class="row text-center">
    <div class="col-sm-8 mt-2 offset-sm-2">
        <h1>{% trans "Profile" %} <em>{{ user_profile.username }}</em></h1>

        <form
            {% if not read_only %}
                method="post" action="{% url 'user_id' user_profile.id %}" enctype="multipart/form-data"
            {% endif %}
        >
            {% if not read_only %}
                {% csrf_token %}
            {% endif %}

            {% include "snippet/form_errors.html" %}

            <fieldset
                    {% if read_only %}
                    disabled
                    {% endif %}
            >
                <div class="row mb-3">
                    <div class="col-6">
                        {# basic user form fields #}

                        {% for field in form %}
                            {% if field.name in lhs_fields %}
                                <div class="row mb-3">
                                    <div class="col-sm-4 text-start">
                                        <label for="id_{{ field.name }}" class="col-form-label">{{ field.label }}</label>
                                    </div>
                                    <div class="col-sm-8">
                                        {{ field }}
                                    </div>
                                </div>
                            {% endif %}
                        {% endfor %}
                    </div>

                    <div class="col-6">
                        {# user avatar field #}

                        {% for field in form %}
                        {% if field.name in img_fields %}
                            <div class="preview">
                                <img src="{{ avatar_url }}" width="100px" height="100px" alt="Avatar image">
                            </div>
                            {{ field }}
                        {% endif %}
                        {% endfor %}

                    </div>
                </div>


                <div class="row mb-3">
                    {% for field in form %}
                        {% if field.name in summernote_fields %}
                        <div class="row mb-3">
                            <div class="col-sm-2 text-start">
                                <label for="{{ field.name }}" class="form-label">{{ field.label }}</label>
                            </div>
                            <div class="col-sm-10">
                                {% if read_only %}
                                    <textarea class="form-control text-start" id="bio" aria-label="biography">
                                        {{ user_profile.bio }}
                                    </textarea>
                                {% else %}
                                    {{ field }}
                                {% endif %}
                            </div>
                        </div>
                        {% endif %}
                    {% endfor %}
                </div>
            </fieldset>
            {% if not read_only %}
            <div class="row mb-3">
                <div class="col-sm-2 offset-sm-3">
                    <a class="btn btn-secondary mb-1" href="{% url 'home' %}">{% trans "Cancel" %}</a>
                </div>
                <div class="col-sm-2 offset-sm-2">
                    <button type="submit" class="btn btn-primary">{% trans "Update" %}</button>
                </div>
            </div>
            {% endif %}
        </form>
    </div>
</div>

{% endblock content %}

{% block extra_js_body %}
    <!-- include summernote js - use bootstrap4 to match settings.SUMMERNOTE_THEME -->
    <script src="{% static 'summernote/summernote-bs4.min.js' %}"></script>
    <!-- lazy loading summernote need to call initSummernote -->
<!--    <script>-->
<!--        $(document).ready(function() {-->
<!--            initSummernote_id_bio();-->
<!--        });-->
<!--    </script>-->

    <script>
        /* Update preview image when file selected.
           Based on https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#examples */

        const input = document.querySelector('#id_avatar'); /* file input */
        const preview = document.querySelector('.preview'); /* div containing preview image */

        function updateImageDisplay() {
            /* Update avatar preview */
            const curFiles = input.files;
            if (curFiles.length === 0) {
                alert("No files currently selected for upload");
            } else {
                for (const file of curFiles) {
                    if (validFileType(file)) {
                        $(".preview img").prop("src", URL.createObjectURL(file));
                    } else {
                        alert(`${file.name} is not a valid file type. Please update your selection.`);
                    }
                }
            }
        }

        // https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types
        const fileTypes = [
            {% for a in image_file_types %}
                "{{ a }}"{% if forloop.revcounter0 > 0 %},{% endif %}
            {% endfor %}
        ];

        function validFileType(file) {
          return fileTypes.includes(file.type);
        }

        function returnFileSize(number) {
          if (number < 1024) {
            return `${number} bytes`;
          } else if (number >= 1024 && number < 1048576) {
            return `${(number / 1024).toFixed(1)} KB`;
          } else if (number >= 1048576) {
            return `${(number / 1048576).toFixed(1)} MB`;
          }
        }

        $(document).ready(function() {
            $('#id_avatar').on('change',
                function(e) {
                    updateImageDisplay();
                });
        });
    </script>


{% endblock extra_js_body %}